export const SUPABASE_URL = 'https://odrduzdebzmuilfsurhk.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kcmR1emRlYnptdWlsZnN1cmhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQwMTQ5MjUsImV4cCI6MjA5OTU5MDkyNX0.NOe-g99hwoOr59nVOZCCl2I4pcKvNt403c3-Fg1mJBQ';
